//
// Created by chuning liu on 4/2/21.
//

#ifndef PROJECT1SFMLTYPE_CONSTANT_H
#define PROJECT1SFMLTYPE_CONSTANT_H
const float SCREEN_WIDTH = 2500;
const float SCREEN_HEIGHT = 2500;
const float UNICODE_DELETE = 8;
const int INPUTBOX_X = 10;
const int INPUTBOX_Y = 950;
const int CURSORX = 10;
const int CURSORY = 950;
const int TEXTINPUTX = 10;
const int TEXTINPUTY = 950;
const int MYTEXTLABLEX = 10;
const int MYTEXTLABLEY = 900;
const int CURSORHEIGHT = 5;
const int CURSORLENGTH = 40;
const int CURSORPOSITIONX = 10;
const int CURSORPOSITIONY = 950;
const int MENUBARWIDTH = 50;
const int MENUBARHEIGHT= 10;
const int MENUBARINPUTBOX_WIDTH = 300;
const int MENUBERINPUTBOX_HEIGHT = 70;
const int SHADOWTEXTX = 450;
const int SHADOWTEXTY = 510;
const int FONTSIZE = 300;
const float TEXTSCALEX = 1.f;
const int DISPLAYBOXSIZEWIDTH = 2500;
const int DISPLAYBOXSIZEHEIGHT = 880;
const int DISPLAYBOXPOSITIONX = 0;
const int DISPLAYBOXPOSITIONY = 0;
const int NORMALTEXTPOSITION_X = 500;
const int NORMALTEXTPOSITION_Y = 500;
const int MENUBARPOSITIONX = 0;
const int NENUBARPOSITIONY = 0;
const int NEWWINDOWFOROPENFILE_WIDTH = 800;
const int NEWWINDOWFOROPENFILE_HEIGHT = 1000;
const int COLORBOXSIZE_WIDTH = 50;
const int COLORBOXSIZE_HEIGHT = 50;
const int HSVSIZE = 512;

#endif //PROJECT1SFMLTYPE_CONSTANT_H
